TaskStatusDB add tasks
OpenFreeEnergy/exorcist pull request #14
Opened 2023-04-22 22:44 UTC by dwhswenson

Resolves #2.

Includes all of #9, so that one should be reviewed first.

NB: Tasks must be added in a reasonable execution order (i.e., topological sort of the DAG), because we use FK constraints on the dependencies table. So no task ID can be added to the dependencies table before it gets added to the tasks table.

2023-07-03 11:33 UTC, richardjgowers requested changes
needs docs on the methods you're adding here.  It's probably worth splitting the sqla class into a separate file too at some point

2023-07-03 11:33 UTC, richardjgowers commented on exorcist/taskdb.py
> +    cursor.close()
document what this does and why it's necessary, probably make it hidden behind an underscore

2023-07-03 11:33 UTC, richardjgowers commented on exorcist/taskdb.py
> +        """
document all parameters

2023-07-03 11:33 UTC, richardjgowers commented on exorcist/taskdb.py
> +        """
document all parameters

2023-07-03 11:33 UTC, richardjgowers commented on exorcist/taskdb.py
> +                 max_tries: int):
requires docs on max_tries here too

2023-07-11 17:11 UTC, dwhswenson commented
Docs updated. This should be ready for another review.

I don't see a point to splitting the SQLA-based implementation into a separate file. Realistically, it is the only implementation we're likely to do, unless SQLA dies.

2023-07-12 08:15 UTC, richardjgowers approved these changes

2023-07-12 08:15 UTC, merged